from __future__ import annotations

import base64
from dataclasses import dataclass
from typing import Optional

import httpx

from app.core.config import settings


class GitHubError(Exception):
    pass


@dataclass
class GitHubRepoInfo:
    owner: str
    name: str
    html_url: str
    clone_url: str
    default_branch: str


class GitHubClient:
    def __init__(
        self,
        token: str,
        owner_type: str,
        owner_name: str,
        api_base_url: str = "https://api.github.com",
    ) -> None:
        if not token:
            raise GitHubError("GITHUB_TOKEN is not set")
        if not owner_name:
            raise GitHubError("GITHUB_OWNER_NAME is not set")

        self.token = token
        self.owner_type = owner_type
        self.owner_name = owner_name
        self.api_base_url = api_base_url.rstrip("/")

        self._headers = {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
        }

    async def _request(self, method: str, path: str, **kwargs) -> httpx.Response:
        url = f"{self.api_base_url}{path}"
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.request(method, url, headers=self._headers, **kwargs)
        if resp.status_code >= 400:
            raise GitHubError(f"{method} {path} failed: {resp.status_code} {resp.text}")
        return resp

    async def ensure_repo(self, repo_name: str, private: bool = True) -> GitHubRepoInfo:
        """
        Ensure a repo exists under the configured owner, creating it if needed.
        """
        owner = self.owner_name

        # 1. Try to get the repo
        path = f"/repos/{owner}/{repo_name}"
        try:
            resp = await self._request("GET", path)
            data = resp.json()
        except GitHubError:
            # 2. Not found -> create
            if self.owner_type == "org":
                create_path = f"/orgs/{owner}/repos"
            else:
                create_path = "/user/repos"

            body = {
                "name": repo_name,
                "private": private,
                "auto_init": True,
                "description": "Converted code generated by MultiLang Behavior Engine.",
            }
            resp = await self._request("POST", create_path, json=body)
            data = resp.json()

        html_url = data["html_url"]
        clone_url = data.get("clone_url") or (
            html_url + ".git" if not html_url.endswith(".git") else html_url
        )

        return GitHubRepoInfo(
            owner=data["owner"]["login"],
            name=data["name"],
            html_url=html_url,
            clone_url=clone_url,
            default_branch=data.get("default_branch", "main"),
        )

    async def create_or_update_file(
        self,
        repo: GitHubRepoInfo,
        path: str,
        content: str,
        commit_message: str,
    ) -> str:
        """
        Create or update a single file using the GitHub Contents API,
        returning the file's HTML URL.
        """
        api_path = f"/repos/{repo.owner}/{repo.name}/contents/{path.lstrip('/')}"
        encoded = base64.b64encode(content.encode("utf-8")).decode("ascii")

        # We first try to GET the file to see if it exists (and get the sha)
        sha: Optional[str] = None
        try:
            resp = await self._request("GET", api_path)
            data = resp.json()
            sha = data.get("sha")
        except GitHubError:
            sha = None

        body = {
            "message": commit_message,
            "content": encoded,
            "branch": repo.default_branch,
        }
        if sha:
            body["sha"] = sha

        resp = await self._request("PUT", api_path, json=body)
        data = resp.json()
        return data["content"]["html_url"]


_github_client: Optional[GitHubClient] = None


def get_github_client() -> GitHubClient:
    """
    Singleton-style GitHub client factory.
    """
    global _github_client
    if _github_client is not None:
        return _github_client

    _github_client = GitHubClient(
        token=settings.GITHUB_TOKEN or "",
        owner_type=settings.GITHUB_OWNER_TYPE,
        owner_name=settings.GITHUB_OWNER_NAME or "",
        api_base_url=settings.GITHUB_API_BASE_URL,
    )
    return _github_client
