# app/services/python_requirements.py
from __future__ import annotations

from typing import Iterable, List

HEADER = """# Auto-generated by MultiLang Behavior Engine
# You can edit this file as needed.
"""

# Core tools we *always* want for Python implementations.
DEFAULT_CORE = ["pytest"]


def _dedupe_preserve_order(items: Iterable[str]) -> List[str]:
    """
    Normalize + dedupe requirement names, preserving first-seen order.
    Case-insensitive, ignores empty lines and comments.
    """
    seen = set()
    out: List[str] = []

    for raw in items:
        if raw is None:
            continue
        name = str(raw).strip()
        if not name or name.startswith("#"):
            continue
        key = name.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(name)

    return out


def build_requirements_contents(
    extra_requirements: Iterable[str] | None = None,
    include_default_core: bool = True,
) -> str:
    """
    Build the final text for requirements.txt.

    - Always includes DEFAULT_CORE (e.g. pytest) if include_default_core is True.
    - Merges in extra_requirements from AI (e.g. ["matplotlib"]).
    - Dedupes while preserving order.
    """
    extras = list(extra_requirements or [])
    core = DEFAULT_CORE if include_default_core else []
    all_reqs = _dedupe_preserve_order(core + extras)

    lines: List[str] = []
    lines.append(HEADER.rstrip())
    lines.append("")
    lines.extend(all_reqs)
    lines.append("")  # trailing newline

    return "\n".join(lines)
